name: innosetup
description: Make windows installer for Flutter & vanilla Dart powered apps powered by Inno Setup.
version: 0.2.0
homepage: https://github.comflowhorn/flutter_innosetup

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  meta: ">=1.17.0"
  version: ^3.0.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
